### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by caicaicai1996** [apachecn/cbianchengnet-ebooks#2]
许多收费的专辑，在文档中无法查看。

**Comment by wizardforcel** [comment]
本来我也就没打算备份收费项目

**Comment by caicaicai1996** [comment]
哈哈哈哈！！！我当时以为发现了新大陆，既然没有收费章节，那不如在网站上看了，效果还好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apachecn/cbianchengnet-ebooks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 下午4:20
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apachecn/cbianchengnet-ebooks] 提示 (Issue #2)





 
本来我也就没打算备份收费项目
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
